name: Monitor de Preços Automático

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y # Conserta dependências se necessário
          
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run price monitor script
        run: python monitor.py

      - name: Commit and push updated data
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/analise_produtos.csv
          # O comando a seguir só faz o commit se houver mudanças no arquivo
          git diff --quiet && git diff --staged --quiet || git commit -m "📊 Atualiza dados de preços"
          git push